### ISSUE TITLE
New Set o Categories

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#10]
Gregor liked idea of fixed set of segmentation labels with one-button selection (Tumor-RtSup, Met-bone, etc).  He felt that the categories may have been too many and is preparing a new set of categories for segmentation.  This set he promised to e-mailed to KM by this evening - 19Jan.

**Comment by kmader** [comment]
Added the categories from the list as shown in https://github.com/4Quant/LungStageAnnotator/blob/master/labels/annotation_labels.json
