### ISSUE TITLE
Studies Identified by AccessionNumber

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#11]
After long discussion - Gregor-Bram, they decided that, although some anonyminity would be lost, it is important that the studies being worked on be identified by their AccessionNumber (0008,0050).  This should appear in the list on page: AnnotationTool, instead of the generic description. 

For example: AccessionNumber should appear in this list, in replacement of or optionally next to the sequencial identifier.  Redundant StudyDescription can be eliminated or optionally left. 

![image](https://cloud.githubusercontent.com/assets/16701211/22106393/cf4bb3a4-de48-11e6-847d-b8196fd90d47.png)

**Comment by drtjre** [comment]
Reminder:  the listing of the accessionNumber is important for the proper selection of study to annotate.  I see it is still missing in the current version.

![screen shot 2017-01-22 at 19 27 45](https://cloud.githubusercontent.com/assets/16701211/22184753/15b314d0-e0d9-11e6-8b11-80e9c832d0bf.png)

**Comment by kmader** [comment]
shows the patient name instead of counter id and lists accession number first
