### ISSUE TITLE
Over-ride automatic Sequence Selection

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#13]
Important is the ability to over-ride the system's choice of CT or PET series to include.  If necessary to choose an alternative sequence from the list of "other" striked-out series (see image below).  This is especially important when no matching sequence is found.

<img width="556" alt="screen shot 2017-01-19 at 10 08 14 am" src="https://cloud.githubusercontent.com/assets/16701211/22106697/51eae9e6-de4a-11e6-9a21-0ebbc5021b73.png">

**Comment by kmader** [comment]
you can now click on the images that make it into the PET and CT list to select which scan you want to load. No clicking loads the first two images. By default the only scans that dont show up are derived

**Comment by drtjre** [comment]
Hi Kevin -
ok will check this out. 

TJ

**Comment by drtjre** [comment]
Should work ok for now - should be sufficient for Alex to review. I will enter a few "enhancements" issues regarding this for future versions which I feel Alex will likely request.
