### ISSUE TITLE
Paint/Erase Tool Requires Radius Selection Buttons

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#14]
When marking with paint or unmarking with erase tool, it is necessary to more precisely select the paint-tool radius as 1, 4, 8 voxels.  Buttons should be provided for this task, as were available in previous versions.

Current version missing radius buttons:
<img width="657" alt="screen shot 2017-01-19 at 1 25 42 pm" src="https://cloud.githubusercontent.com/assets/16701211/22106809/d6aeeaba-de4a-11e6-8c2a-1035ccb36d13.png">

**Comment by kmader** [comment]
fixed in latest version, the dialog is now external and fully resizable
