### ISSUE TITLE
Slice Image Number Display

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#24]
Enhancement:  ImageNumber should be displayed in viewer.

**Comment by kmader** [comment]
maybe a go to slice number would work just as well? Alex had mentioned that the main goal is to be able to find things in reports and sometimes physicians just say the slice number

**Comment by drtjre** [comment]
Sure, I proposed this to Joshy today.   The case Alex was trying to address is when a Report specifies a specific image (ie slice).  In this case, a "goto slice ___" input field would work fine.  You could squeeze it in next to the Pet Opaque input or elsewhere.

TJ

**Comment by drtjre** [comment]
Alex's reaction to "slice number input field": << Would be sufficient to work with reports which specify a specific slice, but I still would like the slice number displayed>> . 

In other words:  A "GOTO SLICE" is necessary.  A display slice is an enhancement.
