### ISSUE TITLE
Cross-Reference hairs 3D

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#4]
Crosshairs should appear in all 3 projections indicating current slice location of other projections.
As one scrolls slices in one projection, these crosshairs should be continuously updated in other two projections.

**Comment by kmader** [comment]
If you hold down the shift key it syncs the view, should I make this behavior the default? I had it on before but I didn't like the other views updating when I didn't want them to

**Comment by drtjre** [comment]
Yes, pls make default.  Radiologists are used to this style.

**Comment by drtjre** [comment]
BTW, correct name "cross-reference-hairs".

**Comment by kmader** [comment]
full-time cross-linked motion does not work (code attempt below didnt work), but basic crosshairs is now implemented

```
def force_linked_motion():
    """
    Make linked motion permanent
    http://slicer-devel.65872.n3.nabble.com/Active-Linked-Motion-permanently-tc4034253.html
    :return:
    """
    # TODO does not work without crosshair node
    crosshairNode = slicer.util.getNode('Crosshair')

    def _onMouseMoved(observer, eventid):
        ras = [0, 0, 0]
        crosshairNode.GetCursorPositionRAS(ras)
        crosshairNode.SetCrosshairRAS(ras)

    crosshairNode.AddObserver(slicer.vtkMRMLCrosshairNode.CursorPositionModifiedEvent, _onMouseMoved)
```
