### ISSUE TITLE
Mark Completed Studies

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#42]
On Initial page - Annotation - would be very helpful to have some indication as to which studies have been previously completed.  Ideally with at timestamp.  
(ie:  2134134  Rossi Mario  -done: 20170201:0800)

**Comment by kmader** [comment]
studies are now crossed out on the list after they are loaded 
![image](https://cloud.githubusercontent.com/assets/116120/22325514/b52e694c-e3ae-11e6-8750-427457b82c12.png), for having it automatically look through folders to find matching names is uglylier and will take considerably more time

**Comment by drtjre** [comment]
Great!  Just tested.   Ideal would be to check existence of completed file - as you mentioned, but this "already opened" works well.  Still need to check if this is consistent after closing Slice-annotator.

**Comment by kmader** [comment]
it won't be, it's just a nice graphical indicator for the samples that have been loaded in the current session. we will anyways need to come up with a more viable solution for tracking the marking of 2000 patients so i don't see any need to make any further developments here
