### ISSUE TITLE
Label Colors

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#7]
Have segmented items use colors where all Tumor types (1-7) are different shades of RED; Nodes with suspected spread are shades of YELLOW; and Mets are shades of BLUE or GREEN.

Allow for multiple selections of the same T/N/M type (ie 2 TumorInfRx) which appear in slightly different shades, while T/N/M's of the different categories should have a more pronounced shade shift.

**Comment by kmader** [comment]
Should the colors be predefined or automatically computed after each new label is added?

**Comment by drtjre** [comment]
The colors should act as a means for the radiologist to confirm that the correct subtype was placed in the correct anatomical position.  Therefore, they should best be PREDEFINED and distinct but grouped accordingly.  

For example:

TrxSup (right superior lobe) : Light Red
TrxMid (right middle lobe): Medium Red
TrxInf   (right inferior lobe): Dark Red

TsxSup (left superior lobe): Light Orange
TsxInf   (left inferior lobe):    Medium Orange

Tacc (accessory Lobe): Dark Orange

Feel free to use your imagination regarding colors - as long as they are distinguishable. 

In the situation where the radiologist wants to create 2 or more of the same subtype.  For example, maybe 3 different suspected primary tumors all in the TrxSup.  In this case, Bram requests that the colors be distinct between these.  I personally would leave them the same because if they overlap, it does not seem to make sense histologically to consider them as two separate tumors and if they do not overlap, one can distinguish them as physically disjoint.  I also think it would also limit the total number of colors for simplicity.

**Comment by kmader** [comment]
fixed colors to be different and consistent for every label set
