### ISSUE TITLE
ToolBox Available

### ISSUE THREAD

**Issue by drtjre** [4Quant/LungStageAnnotator#8]
When in the Slice-Viewer tab, lower-right projection should be empty of image but rather contain options provided on Segmentations page and buttons for adding T/N/M segments with one click.

Several options available.  Will try to create a sketch.  Bram prefers a "vertical" buttons menu.

**Comment by drtjre** [comment]
<img width="1127" alt="seg3dslicer01" src="https://cloud.githubusercontent.com/assets/16701211/22064132/7cba39b0-dd82-11e6-92af-4578d522c36d.png">

**Comment by kmader** [comment]
added dockable panel for segmentation widget
